### ISSUE TITLE
Add new Saxon engine

### ISSUE THREAD

**Issue by adrianmihalko** [joepjoosten/XSL-tester#14]
Anybody knows how to add newer Saxon engine?

I copied /app/net/xsltransform/plugin/Saxon9HEPlugin.java to Saxon98HEPlugin.java.

```
package net.xsltransform.plugin;

import play.Play;

import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerFactory;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.PrintStream;
import java.lang.reflect.InvocationTargetException;

public class Saxon98HEPlugin implements TransformerPlugin{

    private static final String VERSION = "saxon-9.8.0.7-he";

    private static final String TRANSFORMER_FACTORY_CLASS_NAME = "net.sf.saxon.TransformerFactoryImpl";

    private static final ClassLoader saxon98HEClassLoader = new JarClassLoader(new InputStream[]{
            Play.application().resourceAsStream("public/plugins/"+VERSION+"/"+VERSION+".jar")
    }, Saxon98HEPlugin.class.getClassLoader());

    @Override
    public Transformer newTransformer() throws TransformerConfigurationException {
        return TransformerFactory.newInstance(TRANSFORMER_FACTORY_CLASS_NAME, saxon98HEClassLoader).newTransformer();
    }

    @Override
    public Transformer newTransformer(Source source, ByteArrayOutputStream errors) throws TransformerConfigurationException {

        TransformerFactory transformerFactory = TransformerFactory.newInstance(TRANSFORMER_FACTORY_CLASS_NAME, saxon98HEClassLoader);

        try {
            Class FeatureKeysClass = saxon98HEClassLoader.loadClass("net.sf.saxon.lib.FeatureKeys");
            Class ConfigurationClass = saxon98HEClassLoader.loadClass("net.sf.saxon.Configuration");
            Class StandardErrorListenerClass = saxon98HEClassLoader.loadClass("net.sf.saxon.lib.StandardErrorListener");

            Object conf = transformerFactory.getAttribute((String)FeatureKeysClass.getField("CONFIGURATION").get(null));
            Object errorListener = ConfigurationClass.getMethod("getErrorListener").invoke(conf);
            StandardErrorListenerClass.getMethod("setErrorOutput", PrintStream.class).invoke(errorListener, new PrintStream(errors));

            return transformerFactory.newTransformer(source);

        } catch (ClassNotFoundException e) {
            throw new TransformerConfigurationException("net.sf.saxon.TransformerFactoryImpl not found");
        } catch (NoSuchMethodException e) {
            throw new TransformerConfigurationException("net.sf.saxon.TransformerFactoryImpl no such method for error listener");
        } catch (IllegalAccessException e) {
            throw new TransformerConfigurationException("net.sf.saxon.TransformerFactoryImpl not accessible");
        } catch (InvocationTargetException e) {
            throw new TransformerConfigurationException("net.sf.saxon.TransformerFactoryImpl could invoke method for error listener");
        } catch (NoSuchFieldException e) {
            throw new TransformerConfigurationException("net.sf.saxon.TransformerFactoryImpl couldn't get the 'Configuration' field");
        }
    }
}
```

and edited **/app/controller/Application.java**:

I added PLUGINS.put("Saxon98", new Saxon98HEPlugin());

**/app/views/main.scala.html**

I added
```
 <li>
  <a data-engine="Saxon98">Saxon 9.8.0.7</a>
 </li>
```

When I run the app and I select this engine nothing happens, no error, just empty output in the output window.

@joepjoosten do you have any idea how to resolve this issue?

Thank you

**Comment by martin-honnen** [comment]
@adrianmihalko, do you use your local copy of the XSL-tester just to run the XSLT or do you also use the data base feature to store fiddles? If you want to use a new version with support for XSLT 3 based on Saxon 9.8 HE and you use the data base feature, would you want to continue to use the existing data base data with stored fiddles or could you live with a new version and a new data base? Before I put together a .NET based clone of XSL-Tester I also experimented with upgrading the Java based XSL-Tester to current Saxon versions and I have that kind of working, but as it uses different names for the engines, if I make that available on GitHub, it wouldn't allow you to reuse any stored fiddles with the new version, unless you also update your data base to somehow map the old engine names to new ones.

**Comment by adrianmihalko** [comment]
Hi Martin,

" it wouldn't allow you to reuse any stored fiddles with the new version" -> I am not using the save feature, just only in very rare cases. I am using this tool for my hobby projects and I don't need to use the save feature very often. 

It would be awesome if you can release your working version on GitHub.

Is there any specific reason why you switched over .NET version?

**Comment by martin-honnen** [comment]
When I  looked at upgrading the existing Java/Scala Play framework based XSL-Tester to up-to-date Saxon releases I also wanted to host it publically, however I wanted to preserve the ability to run XSLT 1 as well as XSLT 3. As the existing XSLT 1 processors (Saxon 6, Xalan) used with XSL-Tester are hard to restrict to have some secure hosting, as the cloud based hosting of the original XSL-Tester if often down, as the Play framework (I am not in any way familiar with) has moved on several versions, as I on the other hand know how to restrict the XSLT 1 processors like XslCompiledTransform for secure hosting and as I feel more like a .NET than a Java developer anyway, I decided to try to develop a .NET based version. Neverthless I think I will try to release my attempt to upgrade the Java based version to Saxon 9.8 later this week on GitHub, I am struggling a bit on how to use Git to create a branch not containing sensitive data like data base passwords but I think I will get that sorted during the next days.

**Comment by adrianmihalko** [comment]
Thank you very much. I followed you on GitHub, so I get notified after you upload it.

**Comment by adrianmihalko** [comment]
It's now live, thanks to @martin-honnen:

https://github.com/martin-honnen/XSLT-Tester
