### ISSUE TITLE
Love it!

### ISSUE THREAD

**Issue by UgmaDevelopment** [joepjoosten/XSL-tester#16]
Hello!

The only issue with your website is that it's excellent and that it was unavailable earlier today.

Thank you very much for such an excellent way to quickly test XSL. Do you accept small donations?

:tada: :+1:

**Comment by joepjoosten** [comment]
Thanks for the complement. I don't accept small donations. I'm planning to release a lambda based version to lower the hosting costs. And to prevent downtime due to memory use (when large complicated xslt run that need more memory then available on the small server)
